[package]
name = "KahootFinder"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = "0.1"
rand = "0.9.2"
tokio = { version = "1.38", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
quick-js = "0.4"
open = "5.3.2"
